spring:
  application:
    name: Ssenbi
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${test.mariadb.host}:3306/${test.mariadb.database}?serverTimezone=UTC&useUnicode=true&characterEncoding=utf8
    username: ${test.mariadb.username}
    password: ${test.mariadb.pwd}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        globally_quoted_identifiers: true
        format_sql: true
        show_sql: true
    hibernate:
      ddl-auto: update
    open-in-view: true