import type { Metadata } from "next";
import localFont from "next/font/local";
import "./styles/globals.css";
import ResponsiveTabBar from "./components/layout/ResponsiveTabBar";

// todo : 폰트 이쁜 걸로 컨펌!

const geistSans = localFont({
  src: "./assets/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./assets/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ResponsiveTabBar />
        {children}
      </body>
    </html>
  );
}
